services:
  database:
    image: tbongkim03/mariadb:latest
    container_name: movis-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: team5
      MARIADB_PASSWORD: movis
      MARIADB_DATABASE: team5
    volumes:
      - ./src/main/resources/db_config/initdb.d:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql  # 데이터를 유지할 경로
    ports:
      - "6033:3306"

  app:
    container_name: todo-app
    image: tbongkim03/my-webapp:latest
    ports:
      - 8888:8972
    restart: always
    depends_on:
      - database
    links:
      - database
    platform: linux/amd64
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/team5

volumes:
  mariadb_data:

